### ISSUE TITLE
Remove dependency on flight-reactware

### ISSUE THREAD

**Issue by jamesremuscat** [alces-software/flight-store#14]
Rooted in a conversation at https://alces.slack.com/archives/C0BDJJXCL/p1600785207018500:

`flight-store-lib` has a (peer) dependency on `flight-reactware`, which is obsolete and contains a bunch of styles and theme definitions that no longer apply to Flight web properties.

The net result is that anyone using `flight-store-lib` needs to pull all those unwanted styles into their app and then override them.

@mjtko has said that he's happy for Reactware to die a natural death, which implies that any code required by `flight-store-lib` should move to this repo.

**Comment by benarmston** [comment]
Removing the dependency on reactware seemed hard.  It was easier to change reactware into something useful than to try to pick out the components that flight store required from it.  https://github.com/alces-software/flight-reactware/pull/59 removes most everything that was bad with reactware and turns it into a relatively un-opinionated component library.

See 4bf7b11b57c02ae10e84a960dc698ec273f0c794, 2697df21e66f433fbf85022f806efbfb4d3e1adb and b6fd1907bbcda180e0a9c34364e2947423a140ee for the relevant commits in this repo.
